#!/bin/sh
#
# require autoconf > 2.63 & automake >= 1.13
#

export LIBTOOL=/usr/bin/libtool
export AUTOMAKE=/usr/bin/automake
export ACLOCAL=/usr/bin/aclocal

rm -f configure build/*
autoreconf --install

rm -rf po ABOUT-NLS
rm -rf autom4te.cache aclocal.m4 *~

chmod 755 build/*

exit 0
